name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-multi-os:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[lint]
    - name: Run black
      run: black --check --verbose --exclude docs .
    - name: Run flake8
      run: flake8 --exclude docs
    - name: Run pydocstyle
      run: pydocstyle rsaw
    - name: Run sphinx
      run: sphinx-build -W --keep-going docs/ /tmp/foo
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
