name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-multi-os:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: pytest
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
  test-multi-python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - uses: actions/cache@v1
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      run: pytest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
